package phcomm.datasave
{

    public class c1z90021 extends DataSave3D
    {

        public function c1z90021()
        {
            new Vector.<Number>(1)[0] = 72;
            mData.push(new Vector.<Number>(1));
            new Vector.<Number>(9)[0] = 90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = -90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = -90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = -90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = -90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = -90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = -90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = -90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = -90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = -90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 90;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 90;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 90;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 90;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 90;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 90;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 90;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 90;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 90;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -90;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = -90;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = -90;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = -90;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = -90;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = -90;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = -90;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = -90;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = -90;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = -90;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 0;
            new Vector.<Number>(9)[4] = 99;
            new Vector.<Number>(9)[5] = 99;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            mData.fixed = true;
            return;
        }// end function

    }
}
