package phcomm.datasave
{

    public class c1z90081 extends DataSave3D
    {

        public function c1z90081()
        {
            new Vector.<Number>(1)[0] = 30;
            mData.push(new Vector.<Number>(1));
            new Vector.<Number>(9)[0] = 32.492;
            new Vector.<Number>(9)[1] = -100;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 17;
            new Vector.<Number>(9)[5] = 21;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 105.146;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 4;
            new Vector.<Number>(9)[5] = 20;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 105.146;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 7;
            new Vector.<Number>(9)[5] = 25;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 32.492;
            new Vector.<Number>(9)[1] = -100;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 18;
            new Vector.<Number>(9)[5] = 29;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 105.146;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 1;
            new Vector.<Number>(9)[5] = 20;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 32.492;
            new Vector.<Number>(9)[1] = 100;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 8;
            new Vector.<Number>(9)[5] = 24;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 32.492;
            new Vector.<Number>(9)[1] = 100;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 11;
            new Vector.<Number>(9)[5] = 26;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 105.146;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 0;
            new Vector.<Number>(9)[5] = 2;
            new Vector.<Number>(9)[6] = 25;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 32.492;
            new Vector.<Number>(9)[1] = 100;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 5;
            new Vector.<Number>(9)[5] = 24;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -85.065;
            new Vector.<Number>(9)[1] = 61.803;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 12;
            new Vector.<Number>(9)[5] = 23;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -85.065;
            new Vector.<Number>(9)[1] = 61.803;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 15;
            new Vector.<Number>(9)[5] = 27;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 32.492;
            new Vector.<Number>(9)[1] = 100;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 6;
            new Vector.<Number>(9)[5] = 26;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -85.065;
            new Vector.<Number>(9)[1] = 61.803;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 9;
            new Vector.<Number>(9)[5] = 23;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -85.065;
            new Vector.<Number>(9)[1] = -61.803;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 16;
            new Vector.<Number>(9)[5] = 22;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -85.065;
            new Vector.<Number>(9)[1] = -61.803;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 19;
            new Vector.<Number>(9)[5] = 28;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -85.065;
            new Vector.<Number>(9)[1] = 61.803;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 10;
            new Vector.<Number>(9)[5] = 27;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -85.065;
            new Vector.<Number>(9)[1] = -61.803;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 13;
            new Vector.<Number>(9)[5] = 22;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 32.492;
            new Vector.<Number>(9)[1] = -100;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 0;
            new Vector.<Number>(9)[5] = 21;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 32.492;
            new Vector.<Number>(9)[1] = -100;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 3;
            new Vector.<Number>(9)[5] = 29;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -85.065;
            new Vector.<Number>(9)[1] = -61.803;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 14;
            new Vector.<Number>(9)[5] = 28;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 105.146;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 1;
            new Vector.<Number>(9)[5] = 4;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 32.492;
            new Vector.<Number>(9)[1] = -100;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 0;
            new Vector.<Number>(9)[5] = 17;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -85.065;
            new Vector.<Number>(9)[1] = -61.803;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 13;
            new Vector.<Number>(9)[5] = 16;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -85.065;
            new Vector.<Number>(9)[1] = 61.803;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 9;
            new Vector.<Number>(9)[5] = 12;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 32.492;
            new Vector.<Number>(9)[1] = 100;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 5;
            new Vector.<Number>(9)[5] = 8;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 105.146;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 2;
            new Vector.<Number>(9)[5] = 7;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 32.492;
            new Vector.<Number>(9)[1] = 100;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 6;
            new Vector.<Number>(9)[5] = 11;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -85.065;
            new Vector.<Number>(9)[1] = 61.803;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 10;
            new Vector.<Number>(9)[5] = 15;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -85.065;
            new Vector.<Number>(9)[1] = -61.803;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 14;
            new Vector.<Number>(9)[5] = 19;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 32.492;
            new Vector.<Number>(9)[1] = -100;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 3;
            new Vector.<Number>(9)[5] = 18;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            mData.fixed = true;
            return;
        }// end function

    }
}
