package phcomm.datasave
{

    public class c1z90022 extends DataSave3D
    {

        public function c1z90022()
        {
            new Vector.<Number>(1)[0] = 108;
            mData.push(new Vector.<Number>(1));
            new Vector.<Number>(3)[0] = 0;
            new Vector.<Number>(3)[1] = 36;
            new Vector.<Number>(3)[2] = 0;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 1;
            new Vector.<Number>(3)[1] = 37;
            new Vector.<Number>(3)[2] = 1;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 2;
            new Vector.<Number>(3)[1] = 38;
            new Vector.<Number>(3)[2] = 2;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 3;
            new Vector.<Number>(3)[1] = 39;
            new Vector.<Number>(3)[2] = 3;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 4;
            new Vector.<Number>(3)[1] = 40;
            new Vector.<Number>(3)[2] = 4;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 5;
            new Vector.<Number>(3)[1] = 41;
            new Vector.<Number>(3)[2] = 5;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 6;
            new Vector.<Number>(3)[1] = 42;
            new Vector.<Number>(3)[2] = 6;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 7;
            new Vector.<Number>(3)[1] = 43;
            new Vector.<Number>(3)[2] = 7;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 8;
            new Vector.<Number>(3)[1] = 44;
            new Vector.<Number>(3)[2] = 8;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 9;
            new Vector.<Number>(3)[1] = 45;
            new Vector.<Number>(3)[2] = 9;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 10;
            new Vector.<Number>(3)[1] = 46;
            new Vector.<Number>(3)[2] = 10;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 11;
            new Vector.<Number>(3)[1] = 47;
            new Vector.<Number>(3)[2] = 11;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 12;
            new Vector.<Number>(3)[1] = 48;
            new Vector.<Number>(3)[2] = 12;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 13;
            new Vector.<Number>(3)[1] = 49;
            new Vector.<Number>(3)[2] = 13;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 14;
            new Vector.<Number>(3)[1] = 50;
            new Vector.<Number>(3)[2] = 14;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 15;
            new Vector.<Number>(3)[1] = 51;
            new Vector.<Number>(3)[2] = 15;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 16;
            new Vector.<Number>(3)[1] = 52;
            new Vector.<Number>(3)[2] = 16;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 17;
            new Vector.<Number>(3)[1] = 53;
            new Vector.<Number>(3)[2] = 17;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 18;
            new Vector.<Number>(3)[1] = 54;
            new Vector.<Number>(3)[2] = 18;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 19;
            new Vector.<Number>(3)[1] = 55;
            new Vector.<Number>(3)[2] = 19;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 20;
            new Vector.<Number>(3)[1] = 56;
            new Vector.<Number>(3)[2] = 20;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 21;
            new Vector.<Number>(3)[1] = 57;
            new Vector.<Number>(3)[2] = 21;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 22;
            new Vector.<Number>(3)[1] = 58;
            new Vector.<Number>(3)[2] = 22;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 23;
            new Vector.<Number>(3)[1] = 59;
            new Vector.<Number>(3)[2] = 23;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 24;
            new Vector.<Number>(3)[1] = 60;
            new Vector.<Number>(3)[2] = 24;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 25;
            new Vector.<Number>(3)[1] = 61;
            new Vector.<Number>(3)[2] = 25;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 26;
            new Vector.<Number>(3)[1] = 62;
            new Vector.<Number>(3)[2] = 26;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 27;
            new Vector.<Number>(3)[1] = 63;
            new Vector.<Number>(3)[2] = 27;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 28;
            new Vector.<Number>(3)[1] = 64;
            new Vector.<Number>(3)[2] = 28;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 29;
            new Vector.<Number>(3)[1] = 65;
            new Vector.<Number>(3)[2] = 29;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 30;
            new Vector.<Number>(3)[1] = 66;
            new Vector.<Number>(3)[2] = 30;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 31;
            new Vector.<Number>(3)[1] = 67;
            new Vector.<Number>(3)[2] = 31;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 32;
            new Vector.<Number>(3)[1] = 68;
            new Vector.<Number>(3)[2] = 32;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 33;
            new Vector.<Number>(3)[1] = 69;
            new Vector.<Number>(3)[2] = 33;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 34;
            new Vector.<Number>(3)[1] = 70;
            new Vector.<Number>(3)[2] = 34;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 35;
            new Vector.<Number>(3)[1] = 71;
            new Vector.<Number>(3)[2] = 35;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 0;
            new Vector.<Number>(3)[1] = 1;
            new Vector.<Number>(3)[2] = 36;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 1;
            new Vector.<Number>(3)[1] = 2;
            new Vector.<Number>(3)[2] = 37;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 2;
            new Vector.<Number>(3)[1] = 3;
            new Vector.<Number>(3)[2] = 38;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 3;
            new Vector.<Number>(3)[1] = 4;
            new Vector.<Number>(3)[2] = 39;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 4;
            new Vector.<Number>(3)[1] = 5;
            new Vector.<Number>(3)[2] = 40;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 5;
            new Vector.<Number>(3)[1] = 6;
            new Vector.<Number>(3)[2] = 41;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 6;
            new Vector.<Number>(3)[1] = 7;
            new Vector.<Number>(3)[2] = 42;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 7;
            new Vector.<Number>(3)[1] = 8;
            new Vector.<Number>(3)[2] = 43;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 8;
            new Vector.<Number>(3)[1] = 9;
            new Vector.<Number>(3)[2] = 44;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 9;
            new Vector.<Number>(3)[1] = 10;
            new Vector.<Number>(3)[2] = 45;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 10;
            new Vector.<Number>(3)[1] = 11;
            new Vector.<Number>(3)[2] = 46;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 11;
            new Vector.<Number>(3)[1] = 12;
            new Vector.<Number>(3)[2] = 47;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 12;
            new Vector.<Number>(3)[1] = 13;
            new Vector.<Number>(3)[2] = 48;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 13;
            new Vector.<Number>(3)[1] = 14;
            new Vector.<Number>(3)[2] = 49;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 14;
            new Vector.<Number>(3)[1] = 15;
            new Vector.<Number>(3)[2] = 50;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 15;
            new Vector.<Number>(3)[1] = 16;
            new Vector.<Number>(3)[2] = 51;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 16;
            new Vector.<Number>(3)[1] = 17;
            new Vector.<Number>(3)[2] = 52;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 17;
            new Vector.<Number>(3)[1] = 18;
            new Vector.<Number>(3)[2] = 53;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 18;
            new Vector.<Number>(3)[1] = 19;
            new Vector.<Number>(3)[2] = 54;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 19;
            new Vector.<Number>(3)[1] = 20;
            new Vector.<Number>(3)[2] = 55;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 20;
            new Vector.<Number>(3)[1] = 21;
            new Vector.<Number>(3)[2] = 56;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 21;
            new Vector.<Number>(3)[1] = 22;
            new Vector.<Number>(3)[2] = 57;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 22;
            new Vector.<Number>(3)[1] = 23;
            new Vector.<Number>(3)[2] = 58;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 23;
            new Vector.<Number>(3)[1] = 24;
            new Vector.<Number>(3)[2] = 59;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 24;
            new Vector.<Number>(3)[1] = 25;
            new Vector.<Number>(3)[2] = 60;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 25;
            new Vector.<Number>(3)[1] = 26;
            new Vector.<Number>(3)[2] = 61;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 26;
            new Vector.<Number>(3)[1] = 27;
            new Vector.<Number>(3)[2] = 62;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 27;
            new Vector.<Number>(3)[1] = 28;
            new Vector.<Number>(3)[2] = 63;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 28;
            new Vector.<Number>(3)[1] = 29;
            new Vector.<Number>(3)[2] = 64;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 29;
            new Vector.<Number>(3)[1] = 30;
            new Vector.<Number>(3)[2] = 65;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 30;
            new Vector.<Number>(3)[1] = 31;
            new Vector.<Number>(3)[2] = 66;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 31;
            new Vector.<Number>(3)[1] = 32;
            new Vector.<Number>(3)[2] = 67;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 32;
            new Vector.<Number>(3)[1] = 33;
            new Vector.<Number>(3)[2] = 68;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 33;
            new Vector.<Number>(3)[1] = 34;
            new Vector.<Number>(3)[2] = 69;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 34;
            new Vector.<Number>(3)[1] = 35;
            new Vector.<Number>(3)[2] = 70;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 35;
            new Vector.<Number>(3)[1] = 0;
            new Vector.<Number>(3)[2] = 71;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 36;
            new Vector.<Number>(3)[1] = 37;
            new Vector.<Number>(3)[2] = 72;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 37;
            new Vector.<Number>(3)[1] = 38;
            new Vector.<Number>(3)[2] = 73;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 38;
            new Vector.<Number>(3)[1] = 39;
            new Vector.<Number>(3)[2] = 74;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 39;
            new Vector.<Number>(3)[1] = 40;
            new Vector.<Number>(3)[2] = 75;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 40;
            new Vector.<Number>(3)[1] = 41;
            new Vector.<Number>(3)[2] = 76;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 41;
            new Vector.<Number>(3)[1] = 42;
            new Vector.<Number>(3)[2] = 77;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 42;
            new Vector.<Number>(3)[1] = 43;
            new Vector.<Number>(3)[2] = 78;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 43;
            new Vector.<Number>(3)[1] = 44;
            new Vector.<Number>(3)[2] = 79;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 44;
            new Vector.<Number>(3)[1] = 45;
            new Vector.<Number>(3)[2] = 80;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 45;
            new Vector.<Number>(3)[1] = 46;
            new Vector.<Number>(3)[2] = 81;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 46;
            new Vector.<Number>(3)[1] = 47;
            new Vector.<Number>(3)[2] = 82;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 47;
            new Vector.<Number>(3)[1] = 48;
            new Vector.<Number>(3)[2] = 83;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 48;
            new Vector.<Number>(3)[1] = 49;
            new Vector.<Number>(3)[2] = 84;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 49;
            new Vector.<Number>(3)[1] = 50;
            new Vector.<Number>(3)[2] = 85;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 50;
            new Vector.<Number>(3)[1] = 51;
            new Vector.<Number>(3)[2] = 86;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 51;
            new Vector.<Number>(3)[1] = 52;
            new Vector.<Number>(3)[2] = 87;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 52;
            new Vector.<Number>(3)[1] = 53;
            new Vector.<Number>(3)[2] = 88;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 53;
            new Vector.<Number>(3)[1] = 54;
            new Vector.<Number>(3)[2] = 89;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 54;
            new Vector.<Number>(3)[1] = 55;
            new Vector.<Number>(3)[2] = 90;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 55;
            new Vector.<Number>(3)[1] = 56;
            new Vector.<Number>(3)[2] = 91;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 56;
            new Vector.<Number>(3)[1] = 57;
            new Vector.<Number>(3)[2] = 92;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 57;
            new Vector.<Number>(3)[1] = 58;
            new Vector.<Number>(3)[2] = 93;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 58;
            new Vector.<Number>(3)[1] = 59;
            new Vector.<Number>(3)[2] = 94;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 59;
            new Vector.<Number>(3)[1] = 60;
            new Vector.<Number>(3)[2] = 95;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 60;
            new Vector.<Number>(3)[1] = 61;
            new Vector.<Number>(3)[2] = 96;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 61;
            new Vector.<Number>(3)[1] = 62;
            new Vector.<Number>(3)[2] = 97;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 62;
            new Vector.<Number>(3)[1] = 63;
            new Vector.<Number>(3)[2] = 98;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 63;
            new Vector.<Number>(3)[1] = 64;
            new Vector.<Number>(3)[2] = 99;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 64;
            new Vector.<Number>(3)[1] = 65;
            new Vector.<Number>(3)[2] = 100;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 65;
            new Vector.<Number>(3)[1] = 66;
            new Vector.<Number>(3)[2] = 101;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 66;
            new Vector.<Number>(3)[1] = 67;
            new Vector.<Number>(3)[2] = 102;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 67;
            new Vector.<Number>(3)[1] = 68;
            new Vector.<Number>(3)[2] = 103;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 68;
            new Vector.<Number>(3)[1] = 69;
            new Vector.<Number>(3)[2] = 104;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 69;
            new Vector.<Number>(3)[1] = 70;
            new Vector.<Number>(3)[2] = 105;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 70;
            new Vector.<Number>(3)[1] = 71;
            new Vector.<Number>(3)[2] = 106;
            mData.push(new Vector.<Number>(3));
            new Vector.<Number>(3)[0] = 71;
            new Vector.<Number>(3)[1] = 36;
            new Vector.<Number>(3)[2] = 107;
            mData.push(new Vector.<Number>(3));
            mData.fixed = true;
            return;
        }// end function

    }
}
