package phcomm.datasave
{

    public class c1z90051 extends DataSave3D
    {

        public function c1z90051()
        {
            new Vector.<Number>(1)[0] = 16;
            mData.push(new Vector.<Number>(1));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 3;
            new Vector.<Number>(9)[5] = 6;
            new Vector.<Number>(9)[6] = 9;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 90;
            new Vector.<Number>(9)[1] = 90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 5;
            new Vector.<Number>(9)[5] = 13;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 90;
            new Vector.<Number>(9)[1] = -90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 7;
            new Vector.<Number>(9)[5] = 12;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 0;
            new Vector.<Number>(9)[5] = 6;
            new Vector.<Number>(9)[6] = 9;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -90;
            new Vector.<Number>(9)[1] = 90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 11;
            new Vector.<Number>(9)[5] = 14;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 90;
            new Vector.<Number>(9)[1] = 90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 1;
            new Vector.<Number>(9)[5] = 13;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 0;
            new Vector.<Number>(9)[5] = 3;
            new Vector.<Number>(9)[6] = 9;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 90;
            new Vector.<Number>(9)[1] = -90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 2;
            new Vector.<Number>(9)[5] = 12;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -90;
            new Vector.<Number>(9)[1] = -90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 10;
            new Vector.<Number>(9)[5] = 15;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 110;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 0;
            new Vector.<Number>(9)[5] = 3;
            new Vector.<Number>(9)[6] = 6;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -90;
            new Vector.<Number>(9)[1] = -90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 8;
            new Vector.<Number>(9)[5] = 15;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -90;
            new Vector.<Number>(9)[1] = 90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 4;
            new Vector.<Number>(9)[5] = 14;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 90;
            new Vector.<Number>(9)[1] = -90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 2;
            new Vector.<Number>(9)[5] = 7;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 90;
            new Vector.<Number>(9)[1] = 90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 1;
            new Vector.<Number>(9)[5] = 5;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -90;
            new Vector.<Number>(9)[1] = 90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 4;
            new Vector.<Number>(9)[5] = 11;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -90;
            new Vector.<Number>(9)[1] = -90;
            new Vector.<Number>(9)[2] = -110;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 8;
            new Vector.<Number>(9)[5] = 10;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            mData.fixed = true;
            return;
        }// end function

    }
}
