package phcomm.datasave
{

    public class c1z90151 extends DataSave3D
    {

        public function c1z90151()
        {
            new Vector.<Number>(1)[0] = 60;
            mData.push(new Vector.<Number>(1));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 133.148;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 3;
            new Vector.<Number>(9)[5] = 6;
            new Vector.<Number>(9)[6] = 9;
            new Vector.<Number>(9)[7] = 12;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 96.347;
            new Vector.<Number>(9)[1] = 70;
            new Vector.<Number>(9)[2] = 59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 14;
            new Vector.<Number>(9)[5] = 17;
            new Vector.<Number>(9)[6] = 40;
            new Vector.<Number>(9)[7] = 42;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 96.347;
            new Vector.<Number>(9)[1] = -70;
            new Vector.<Number>(9)[2] = 59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 4;
            new Vector.<Number>(9)[5] = 16;
            new Vector.<Number>(9)[6] = 18;
            new Vector.<Number>(9)[7] = 23;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 133.148;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 0;
            new Vector.<Number>(9)[5] = 6;
            new Vector.<Number>(9)[6] = 9;
            new Vector.<Number>(9)[7] = 12;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 96.347;
            new Vector.<Number>(9)[1] = -70;
            new Vector.<Number>(9)[2] = 59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 2;
            new Vector.<Number>(9)[5] = 16;
            new Vector.<Number>(9)[6] = 18;
            new Vector.<Number>(9)[7] = 23;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -36.801;
            new Vector.<Number>(9)[1] = -113.262;
            new Vector.<Number>(9)[2] = 59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 7;
            new Vector.<Number>(9)[5] = 22;
            new Vector.<Number>(9)[6] = 24;
            new Vector.<Number>(9)[7] = 29;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 133.148;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 0;
            new Vector.<Number>(9)[5] = 3;
            new Vector.<Number>(9)[6] = 9;
            new Vector.<Number>(9)[7] = 12;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -36.801;
            new Vector.<Number>(9)[1] = -113.262;
            new Vector.<Number>(9)[2] = 59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 5;
            new Vector.<Number>(9)[5] = 22;
            new Vector.<Number>(9)[6] = 24;
            new Vector.<Number>(9)[7] = 29;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -119.091;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 10;
            new Vector.<Number>(9)[5] = 28;
            new Vector.<Number>(9)[6] = 30;
            new Vector.<Number>(9)[7] = 35;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 133.148;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 0;
            new Vector.<Number>(9)[5] = 3;
            new Vector.<Number>(9)[6] = 6;
            new Vector.<Number>(9)[7] = 12;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -119.091;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 8;
            new Vector.<Number>(9)[5] = 28;
            new Vector.<Number>(9)[6] = 30;
            new Vector.<Number>(9)[7] = 35;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -36.801;
            new Vector.<Number>(9)[1] = 113.262;
            new Vector.<Number>(9)[2] = 59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 13;
            new Vector.<Number>(9)[5] = 34;
            new Vector.<Number>(9)[6] = 36;
            new Vector.<Number>(9)[7] = 41;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 133.148;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 0;
            new Vector.<Number>(9)[5] = 3;
            new Vector.<Number>(9)[6] = 6;
            new Vector.<Number>(9)[7] = 9;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -36.801;
            new Vector.<Number>(9)[1] = 113.262;
            new Vector.<Number>(9)[2] = 59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 11;
            new Vector.<Number>(9)[5] = 34;
            new Vector.<Number>(9)[6] = 36;
            new Vector.<Number>(9)[7] = 41;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 96.347;
            new Vector.<Number>(9)[1] = 70;
            new Vector.<Number>(9)[2] = 59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 1;
            new Vector.<Number>(9)[5] = 17;
            new Vector.<Number>(9)[6] = 40;
            new Vector.<Number>(9)[7] = 42;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 119.091;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 19;
            new Vector.<Number>(9)[5] = 44;
            new Vector.<Number>(9)[6] = 47;
            new Vector.<Number>(9)[7] = 58;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 96.347;
            new Vector.<Number>(9)[1] = -70;
            new Vector.<Number>(9)[2] = 59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 2;
            new Vector.<Number>(9)[5] = 4;
            new Vector.<Number>(9)[6] = 18;
            new Vector.<Number>(9)[7] = 23;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 96.347;
            new Vector.<Number>(9)[1] = 70;
            new Vector.<Number>(9)[2] = 59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 1;
            new Vector.<Number>(9)[5] = 14;
            new Vector.<Number>(9)[6] = 40;
            new Vector.<Number>(9)[7] = 42;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 96.347;
            new Vector.<Number>(9)[1] = -70;
            new Vector.<Number>(9)[2] = 59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 2;
            new Vector.<Number>(9)[5] = 4;
            new Vector.<Number>(9)[6] = 16;
            new Vector.<Number>(9)[7] = 23;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 119.091;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 15;
            new Vector.<Number>(9)[5] = 44;
            new Vector.<Number>(9)[6] = 47;
            new Vector.<Number>(9)[7] = 58;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 36.801;
            new Vector.<Number>(9)[1] = -113.262;
            new Vector.<Number>(9)[2] = -59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 21;
            new Vector.<Number>(9)[5] = 25;
            new Vector.<Number>(9)[6] = 46;
            new Vector.<Number>(9)[7] = 50;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 36.801;
            new Vector.<Number>(9)[1] = -113.262;
            new Vector.<Number>(9)[2] = -59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 20;
            new Vector.<Number>(9)[5] = 25;
            new Vector.<Number>(9)[6] = 46;
            new Vector.<Number>(9)[7] = 50;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -36.801;
            new Vector.<Number>(9)[1] = -113.262;
            new Vector.<Number>(9)[2] = 59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 5;
            new Vector.<Number>(9)[5] = 7;
            new Vector.<Number>(9)[6] = 24;
            new Vector.<Number>(9)[7] = 29;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 96.347;
            new Vector.<Number>(9)[1] = -70;
            new Vector.<Number>(9)[2] = 59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 2;
            new Vector.<Number>(9)[5] = 4;
            new Vector.<Number>(9)[6] = 16;
            new Vector.<Number>(9)[7] = 18;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -36.801;
            new Vector.<Number>(9)[1] = -113.262;
            new Vector.<Number>(9)[2] = 59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 5;
            new Vector.<Number>(9)[5] = 7;
            new Vector.<Number>(9)[6] = 22;
            new Vector.<Number>(9)[7] = 29;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 36.801;
            new Vector.<Number>(9)[1] = -113.262;
            new Vector.<Number>(9)[2] = -59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 20;
            new Vector.<Number>(9)[5] = 21;
            new Vector.<Number>(9)[6] = 46;
            new Vector.<Number>(9)[7] = 50;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -96.347;
            new Vector.<Number>(9)[1] = -70;
            new Vector.<Number>(9)[2] = -59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 27;
            new Vector.<Number>(9)[5] = 31;
            new Vector.<Number>(9)[6] = 49;
            new Vector.<Number>(9)[7] = 53;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -96.347;
            new Vector.<Number>(9)[1] = -70;
            new Vector.<Number>(9)[2] = -59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 26;
            new Vector.<Number>(9)[5] = 31;
            new Vector.<Number>(9)[6] = 49;
            new Vector.<Number>(9)[7] = 53;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -119.091;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 8;
            new Vector.<Number>(9)[5] = 10;
            new Vector.<Number>(9)[6] = 30;
            new Vector.<Number>(9)[7] = 35;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -36.801;
            new Vector.<Number>(9)[1] = -113.262;
            new Vector.<Number>(9)[2] = 59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 5;
            new Vector.<Number>(9)[5] = 7;
            new Vector.<Number>(9)[6] = 22;
            new Vector.<Number>(9)[7] = 24;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -119.091;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 8;
            new Vector.<Number>(9)[5] = 10;
            new Vector.<Number>(9)[6] = 28;
            new Vector.<Number>(9)[7] = 35;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -96.347;
            new Vector.<Number>(9)[1] = -70;
            new Vector.<Number>(9)[2] = -59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 26;
            new Vector.<Number>(9)[5] = 27;
            new Vector.<Number>(9)[6] = 49;
            new Vector.<Number>(9)[7] = 53;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -96.347;
            new Vector.<Number>(9)[1] = 70;
            new Vector.<Number>(9)[2] = -59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 33;
            new Vector.<Number>(9)[5] = 37;
            new Vector.<Number>(9)[6] = 52;
            new Vector.<Number>(9)[7] = 56;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -96.347;
            new Vector.<Number>(9)[1] = 70;
            new Vector.<Number>(9)[2] = -59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 32;
            new Vector.<Number>(9)[5] = 37;
            new Vector.<Number>(9)[6] = 52;
            new Vector.<Number>(9)[7] = 56;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -36.801;
            new Vector.<Number>(9)[1] = 113.262;
            new Vector.<Number>(9)[2] = 59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 11;
            new Vector.<Number>(9)[5] = 13;
            new Vector.<Number>(9)[6] = 36;
            new Vector.<Number>(9)[7] = 41;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -119.091;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 8;
            new Vector.<Number>(9)[5] = 10;
            new Vector.<Number>(9)[6] = 28;
            new Vector.<Number>(9)[7] = 30;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -36.801;
            new Vector.<Number>(9)[1] = 113.262;
            new Vector.<Number>(9)[2] = 59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 11;
            new Vector.<Number>(9)[5] = 13;
            new Vector.<Number>(9)[6] = 34;
            new Vector.<Number>(9)[7] = 41;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -96.347;
            new Vector.<Number>(9)[1] = 70;
            new Vector.<Number>(9)[2] = -59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 32;
            new Vector.<Number>(9)[5] = 33;
            new Vector.<Number>(9)[6] = 52;
            new Vector.<Number>(9)[7] = 56;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 36.801;
            new Vector.<Number>(9)[1] = 113.262;
            new Vector.<Number>(9)[2] = -59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 39;
            new Vector.<Number>(9)[5] = 43;
            new Vector.<Number>(9)[6] = 55;
            new Vector.<Number>(9)[7] = 59;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 36.801;
            new Vector.<Number>(9)[1] = 113.262;
            new Vector.<Number>(9)[2] = -59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 38;
            new Vector.<Number>(9)[5] = 43;
            new Vector.<Number>(9)[6] = 55;
            new Vector.<Number>(9)[7] = 59;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 96.347;
            new Vector.<Number>(9)[1] = 70;
            new Vector.<Number>(9)[2] = 59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 1;
            new Vector.<Number>(9)[5] = 14;
            new Vector.<Number>(9)[6] = 17;
            new Vector.<Number>(9)[7] = 42;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -36.801;
            new Vector.<Number>(9)[1] = 113.262;
            new Vector.<Number>(9)[2] = 59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 11;
            new Vector.<Number>(9)[5] = 13;
            new Vector.<Number>(9)[6] = 34;
            new Vector.<Number>(9)[7] = 36;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 96.347;
            new Vector.<Number>(9)[1] = 70;
            new Vector.<Number>(9)[2] = 59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 1;
            new Vector.<Number>(9)[5] = 14;
            new Vector.<Number>(9)[6] = 17;
            new Vector.<Number>(9)[7] = 40;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 36.801;
            new Vector.<Number>(9)[1] = 113.262;
            new Vector.<Number>(9)[2] = -59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 38;
            new Vector.<Number>(9)[5] = 39;
            new Vector.<Number>(9)[6] = 55;
            new Vector.<Number>(9)[7] = 59;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 119.091;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 15;
            new Vector.<Number>(9)[5] = 19;
            new Vector.<Number>(9)[6] = 47;
            new Vector.<Number>(9)[7] = 58;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -133.148;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 48;
            new Vector.<Number>(9)[5] = 51;
            new Vector.<Number>(9)[6] = 54;
            new Vector.<Number>(9)[7] = 57;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 36.801;
            new Vector.<Number>(9)[1] = -113.262;
            new Vector.<Number>(9)[2] = -59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 20;
            new Vector.<Number>(9)[5] = 21;
            new Vector.<Number>(9)[6] = 25;
            new Vector.<Number>(9)[7] = 50;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 119.091;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 15;
            new Vector.<Number>(9)[5] = 19;
            new Vector.<Number>(9)[6] = 44;
            new Vector.<Number>(9)[7] = 58;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -133.148;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 45;
            new Vector.<Number>(9)[5] = 51;
            new Vector.<Number>(9)[6] = 54;
            new Vector.<Number>(9)[7] = 57;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -96.347;
            new Vector.<Number>(9)[1] = -70;
            new Vector.<Number>(9)[2] = -59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 26;
            new Vector.<Number>(9)[5] = 27;
            new Vector.<Number>(9)[6] = 31;
            new Vector.<Number>(9)[7] = 53;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 36.801;
            new Vector.<Number>(9)[1] = -113.262;
            new Vector.<Number>(9)[2] = -59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 20;
            new Vector.<Number>(9)[5] = 21;
            new Vector.<Number>(9)[6] = 25;
            new Vector.<Number>(9)[7] = 46;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -133.148;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 45;
            new Vector.<Number>(9)[5] = 48;
            new Vector.<Number>(9)[6] = 54;
            new Vector.<Number>(9)[7] = 57;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -96.347;
            new Vector.<Number>(9)[1] = 70;
            new Vector.<Number>(9)[2] = -59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 32;
            new Vector.<Number>(9)[5] = 33;
            new Vector.<Number>(9)[6] = 37;
            new Vector.<Number>(9)[7] = 56;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -96.347;
            new Vector.<Number>(9)[1] = -70;
            new Vector.<Number>(9)[2] = -59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 26;
            new Vector.<Number>(9)[5] = 27;
            new Vector.<Number>(9)[6] = 31;
            new Vector.<Number>(9)[7] = 49;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -133.148;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 45;
            new Vector.<Number>(9)[5] = 48;
            new Vector.<Number>(9)[6] = 51;
            new Vector.<Number>(9)[7] = 57;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 36.801;
            new Vector.<Number>(9)[1] = 113.262;
            new Vector.<Number>(9)[2] = -59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 38;
            new Vector.<Number>(9)[5] = 39;
            new Vector.<Number>(9)[6] = 43;
            new Vector.<Number>(9)[7] = 59;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -96.347;
            new Vector.<Number>(9)[1] = 70;
            new Vector.<Number>(9)[2] = -59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 32;
            new Vector.<Number>(9)[5] = 33;
            new Vector.<Number>(9)[6] = 37;
            new Vector.<Number>(9)[7] = 52;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -133.148;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 45;
            new Vector.<Number>(9)[5] = 48;
            new Vector.<Number>(9)[6] = 51;
            new Vector.<Number>(9)[7] = 54;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 119.091;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 15;
            new Vector.<Number>(9)[5] = 19;
            new Vector.<Number>(9)[6] = 44;
            new Vector.<Number>(9)[7] = 47;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 36.801;
            new Vector.<Number>(9)[1] = 113.262;
            new Vector.<Number>(9)[2] = -59.546;
            new Vector.<Number>(9)[3] = 4;
            new Vector.<Number>(9)[4] = 38;
            new Vector.<Number>(9)[5] = 39;
            new Vector.<Number>(9)[6] = 43;
            new Vector.<Number>(9)[7] = 55;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            mData.fixed = true;
            return;
        }// end function

    }
}
