package phcomm.datasave
{

    public class c1z90131 extends DataSave3D
    {

        public function c1z90131()
        {
            new Vector.<Number>(1)[0] = 24;
            mData.push(new Vector.<Number>(1));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 141.42;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 3;
            new Vector.<Number>(9)[5] = 6;
            new Vector.<Number>(9)[6] = 9;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 141.42;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 0;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 11;
            new Vector.<Number>(9)[5] = 14;
            new Vector.<Number>(9)[6] = 22;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = -141.42;
            new Vector.<Number>(9)[2] = 0;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 4;
            new Vector.<Number>(9)[5] = 13;
            new Vector.<Number>(9)[6] = 17;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 141.42;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 0;
            new Vector.<Number>(9)[5] = 6;
            new Vector.<Number>(9)[6] = 9;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = -141.42;
            new Vector.<Number>(9)[2] = 0;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 2;
            new Vector.<Number>(9)[5] = 13;
            new Vector.<Number>(9)[6] = 17;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -141.42;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 0;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 7;
            new Vector.<Number>(9)[5] = 16;
            new Vector.<Number>(9)[6] = 20;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 141.42;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 0;
            new Vector.<Number>(9)[5] = 3;
            new Vector.<Number>(9)[6] = 9;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -141.42;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 0;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 5;
            new Vector.<Number>(9)[5] = 16;
            new Vector.<Number>(9)[6] = 20;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 141.42;
            new Vector.<Number>(9)[2] = 0;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 10;
            new Vector.<Number>(9)[5] = 19;
            new Vector.<Number>(9)[6] = 23;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 141.42;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 0;
            new Vector.<Number>(9)[5] = 3;
            new Vector.<Number>(9)[6] = 6;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 141.42;
            new Vector.<Number>(9)[2] = 0;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 8;
            new Vector.<Number>(9)[5] = 19;
            new Vector.<Number>(9)[6] = 23;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 141.42;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 0;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 1;
            new Vector.<Number>(9)[5] = 14;
            new Vector.<Number>(9)[6] = 22;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -141.42;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 15;
            new Vector.<Number>(9)[5] = 18;
            new Vector.<Number>(9)[6] = 21;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = -141.42;
            new Vector.<Number>(9)[2] = 0;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 2;
            new Vector.<Number>(9)[5] = 4;
            new Vector.<Number>(9)[6] = 17;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 141.42;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 0;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 1;
            new Vector.<Number>(9)[5] = 11;
            new Vector.<Number>(9)[6] = 22;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -141.42;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 12;
            new Vector.<Number>(9)[5] = 18;
            new Vector.<Number>(9)[6] = 21;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -141.42;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 0;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 5;
            new Vector.<Number>(9)[5] = 7;
            new Vector.<Number>(9)[6] = 20;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = -141.42;
            new Vector.<Number>(9)[2] = 0;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 2;
            new Vector.<Number>(9)[5] = 4;
            new Vector.<Number>(9)[6] = 13;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -141.42;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 12;
            new Vector.<Number>(9)[5] = 15;
            new Vector.<Number>(9)[6] = 21;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 141.42;
            new Vector.<Number>(9)[2] = 0;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 8;
            new Vector.<Number>(9)[5] = 10;
            new Vector.<Number>(9)[6] = 23;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -141.42;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 0;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 5;
            new Vector.<Number>(9)[5] = 7;
            new Vector.<Number>(9)[6] = 16;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -141.42;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 12;
            new Vector.<Number>(9)[5] = 15;
            new Vector.<Number>(9)[6] = 18;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 141.42;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 0;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 1;
            new Vector.<Number>(9)[5] = 11;
            new Vector.<Number>(9)[6] = 14;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 0;
            new Vector.<Number>(9)[1] = 141.42;
            new Vector.<Number>(9)[2] = 0;
            new Vector.<Number>(9)[3] = 3;
            new Vector.<Number>(9)[4] = 8;
            new Vector.<Number>(9)[5] = 10;
            new Vector.<Number>(9)[6] = 19;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            mData.fixed = true;
            return;
        }// end function

    }
}
