package phcomm.datasave
{

    public class c1z90141 extends DataSave3D
    {

        public function c1z90141()
        {
            new Vector.<Number>(1)[0] = 60;
            mData.push(new Vector.<Number>(1));
            new Vector.<Number>(9)[0] = 85.07;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 10;
            new Vector.<Number>(9)[5] = 34;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 26.29;
            new Vector.<Number>(9)[1] = -80.9;
            new Vector.<Number>(9)[2] = 111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 14;
            new Vector.<Number>(9)[5] = 15;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -68.82;
            new Vector.<Number>(9)[1] = -50;
            new Vector.<Number>(9)[2] = 111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 19;
            new Vector.<Number>(9)[5] = 20;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -68.82;
            new Vector.<Number>(9)[1] = 50;
            new Vector.<Number>(9)[2] = 111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 24;
            new Vector.<Number>(9)[5] = 25;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 26.29;
            new Vector.<Number>(9)[1] = 80.9;
            new Vector.<Number>(9)[2] = 111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 29;
            new Vector.<Number>(9)[5] = 30;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -85.07;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 43;
            new Vector.<Number>(9)[5] = 47;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -26.29;
            new Vector.<Number>(9)[1] = -80.9;
            new Vector.<Number>(9)[2] = -111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 38;
            new Vector.<Number>(9)[5] = 42;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 68.82;
            new Vector.<Number>(9)[1] = -50;
            new Vector.<Number>(9)[2] = -111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 37;
            new Vector.<Number>(9)[5] = 58;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 68.82;
            new Vector.<Number>(9)[1] = 50;
            new Vector.<Number>(9)[2] = -111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 53;
            new Vector.<Number>(9)[5] = 57;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -26.29;
            new Vector.<Number>(9)[1] = 80.9;
            new Vector.<Number>(9)[2] = -111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 48;
            new Vector.<Number>(9)[5] = 52;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 85.07;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 0;
            new Vector.<Number>(9)[5] = 34;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 137.64;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 33;
            new Vector.<Number>(9)[5] = 55;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 111.35;
            new Vector.<Number>(9)[1] = -80.9;
            new Vector.<Number>(9)[2] = -26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 36;
            new Vector.<Number>(9)[5] = 59;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 42.53;
            new Vector.<Number>(9)[1] = -130.9;
            new Vector.<Number>(9)[2] = 26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 16;
            new Vector.<Number>(9)[5] = 35;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 26.29;
            new Vector.<Number>(9)[1] = -80.9;
            new Vector.<Number>(9)[2] = 111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 1;
            new Vector.<Number>(9)[5] = 15;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 26.29;
            new Vector.<Number>(9)[1] = -80.9;
            new Vector.<Number>(9)[2] = 111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 1;
            new Vector.<Number>(9)[5] = 14;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 42.53;
            new Vector.<Number>(9)[1] = -130.9;
            new Vector.<Number>(9)[2] = 26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 13;
            new Vector.<Number>(9)[5] = 35;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -42.53;
            new Vector.<Number>(9)[1] = -130.9;
            new Vector.<Number>(9)[2] = -26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 39;
            new Vector.<Number>(9)[5] = 41;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -111.35;
            new Vector.<Number>(9)[1] = -80.9;
            new Vector.<Number>(9)[2] = 26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 21;
            new Vector.<Number>(9)[5] = 40;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -68.82;
            new Vector.<Number>(9)[1] = -50;
            new Vector.<Number>(9)[2] = 111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 2;
            new Vector.<Number>(9)[5] = 20;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -68.82;
            new Vector.<Number>(9)[1] = -50;
            new Vector.<Number>(9)[2] = 111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 2;
            new Vector.<Number>(9)[5] = 19;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -111.35;
            new Vector.<Number>(9)[1] = -80.9;
            new Vector.<Number>(9)[2] = 26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 18;
            new Vector.<Number>(9)[5] = 40;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -137.64;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 44;
            new Vector.<Number>(9)[5] = 46;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -111.35;
            new Vector.<Number>(9)[1] = 80.9;
            new Vector.<Number>(9)[2] = 26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 26;
            new Vector.<Number>(9)[5] = 45;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -68.82;
            new Vector.<Number>(9)[1] = 50;
            new Vector.<Number>(9)[2] = 111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 3;
            new Vector.<Number>(9)[5] = 25;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -68.82;
            new Vector.<Number>(9)[1] = 50;
            new Vector.<Number>(9)[2] = 111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 3;
            new Vector.<Number>(9)[5] = 24;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -111.35;
            new Vector.<Number>(9)[1] = 80.9;
            new Vector.<Number>(9)[2] = 26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 23;
            new Vector.<Number>(9)[5] = 45;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -42.53;
            new Vector.<Number>(9)[1] = 130.9;
            new Vector.<Number>(9)[2] = -26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 49;
            new Vector.<Number>(9)[5] = 51;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 42.53;
            new Vector.<Number>(9)[1] = 130.9;
            new Vector.<Number>(9)[2] = 26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 31;
            new Vector.<Number>(9)[5] = 50;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 26.29;
            new Vector.<Number>(9)[1] = 80.9;
            new Vector.<Number>(9)[2] = 111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 4;
            new Vector.<Number>(9)[5] = 30;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 26.29;
            new Vector.<Number>(9)[1] = 80.9;
            new Vector.<Number>(9)[2] = 111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 4;
            new Vector.<Number>(9)[5] = 29;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 42.53;
            new Vector.<Number>(9)[1] = 130.9;
            new Vector.<Number>(9)[2] = 26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 28;
            new Vector.<Number>(9)[5] = 50;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 111.35;
            new Vector.<Number>(9)[1] = 80.9;
            new Vector.<Number>(9)[2] = -26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 54;
            new Vector.<Number>(9)[5] = 56;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 137.64;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 11;
            new Vector.<Number>(9)[5] = 55;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 85.07;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 0;
            new Vector.<Number>(9)[5] = 10;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 42.53;
            new Vector.<Number>(9)[1] = -130.9;
            new Vector.<Number>(9)[2] = 26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 13;
            new Vector.<Number>(9)[5] = 16;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 111.35;
            new Vector.<Number>(9)[1] = -80.9;
            new Vector.<Number>(9)[2] = -26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 12;
            new Vector.<Number>(9)[5] = 59;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 68.82;
            new Vector.<Number>(9)[1] = -50;
            new Vector.<Number>(9)[2] = -111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 7;
            new Vector.<Number>(9)[5] = 58;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -26.29;
            new Vector.<Number>(9)[1] = -80.9;
            new Vector.<Number>(9)[2] = -111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 6;
            new Vector.<Number>(9)[5] = 42;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -42.53;
            new Vector.<Number>(9)[1] = -130.9;
            new Vector.<Number>(9)[2] = -26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 17;
            new Vector.<Number>(9)[5] = 41;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -111.35;
            new Vector.<Number>(9)[1] = -80.9;
            new Vector.<Number>(9)[2] = 26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 18;
            new Vector.<Number>(9)[5] = 21;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -42.53;
            new Vector.<Number>(9)[1] = -130.9;
            new Vector.<Number>(9)[2] = -26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 17;
            new Vector.<Number>(9)[5] = 39;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -26.29;
            new Vector.<Number>(9)[1] = -80.9;
            new Vector.<Number>(9)[2] = -111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 6;
            new Vector.<Number>(9)[5] = 38;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -85.07;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 5;
            new Vector.<Number>(9)[5] = 47;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -137.64;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 22;
            new Vector.<Number>(9)[5] = 46;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -111.35;
            new Vector.<Number>(9)[1] = 80.9;
            new Vector.<Number>(9)[2] = 26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 23;
            new Vector.<Number>(9)[5] = 26;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -137.64;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 22;
            new Vector.<Number>(9)[5] = 44;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -85.07;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = -111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 5;
            new Vector.<Number>(9)[5] = 43;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -26.29;
            new Vector.<Number>(9)[1] = 80.9;
            new Vector.<Number>(9)[2] = -111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 9;
            new Vector.<Number>(9)[5] = 52;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -42.53;
            new Vector.<Number>(9)[1] = 130.9;
            new Vector.<Number>(9)[2] = -26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 27;
            new Vector.<Number>(9)[5] = 51;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 42.53;
            new Vector.<Number>(9)[1] = 130.9;
            new Vector.<Number>(9)[2] = 26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 28;
            new Vector.<Number>(9)[5] = 31;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -42.53;
            new Vector.<Number>(9)[1] = 130.9;
            new Vector.<Number>(9)[2] = -26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 27;
            new Vector.<Number>(9)[5] = 49;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = -26.29;
            new Vector.<Number>(9)[1] = 80.9;
            new Vector.<Number>(9)[2] = -111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 9;
            new Vector.<Number>(9)[5] = 48;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 68.82;
            new Vector.<Number>(9)[1] = 50;
            new Vector.<Number>(9)[2] = -111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 8;
            new Vector.<Number>(9)[5] = 57;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 111.35;
            new Vector.<Number>(9)[1] = 80.9;
            new Vector.<Number>(9)[2] = -26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 32;
            new Vector.<Number>(9)[5] = 56;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 137.64;
            new Vector.<Number>(9)[1] = 0;
            new Vector.<Number>(9)[2] = 26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 11;
            new Vector.<Number>(9)[5] = 33;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 111.35;
            new Vector.<Number>(9)[1] = 80.9;
            new Vector.<Number>(9)[2] = -26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 32;
            new Vector.<Number>(9)[5] = 54;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 68.82;
            new Vector.<Number>(9)[1] = 50;
            new Vector.<Number>(9)[2] = -111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 8;
            new Vector.<Number>(9)[5] = 53;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 68.82;
            new Vector.<Number>(9)[1] = -50;
            new Vector.<Number>(9)[2] = -111.35;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 7;
            new Vector.<Number>(9)[5] = 37;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            new Vector.<Number>(9)[0] = 111.35;
            new Vector.<Number>(9)[1] = -80.9;
            new Vector.<Number>(9)[2] = -26.29;
            new Vector.<Number>(9)[3] = 2;
            new Vector.<Number>(9)[4] = 12;
            new Vector.<Number>(9)[5] = 36;
            new Vector.<Number>(9)[6] = 99;
            new Vector.<Number>(9)[7] = 99;
            new Vector.<Number>(9)[8] = 99;
            mData.push(new Vector.<Number>(9));
            mData.fixed = true;
            return;
        }// end function

    }
}
